apiVersion: v1
kind: Pod
metadata:
  name: firefox
  labels:
    app.kubernetes.io/name: firefox
spec:
  containers:
  - name: firefox
    image: lscr.io/linuxserver/firefox:latest
    ports:
      - containerPort: 3000
